global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['my-exporter-one:9100']
      - targets: ['my-exporter-two:9101']